/**
 * NexVault — BiometricManager
 * 
 * Handles WebAuthn interactions specifically utilizing the PRF (Pseudo-Random Function) extension
 * to derive a symmetric key bound to the user's biometric authenticator.
 */

import cryptoEngine from './CryptoEngine.js';

class BiometricManager {
  /**
   * Check if WebAuthn PRF is supported by the current browser/device.
   */
  async isPrfSupported() {
    if (!window.PublicKeyCredential) return false;
    
    // Check if the authenticator supports the 'prf' extension
    try {
      const isSupported = await window.PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
      return isSupported; // Note: PRF support isn't strictly guaranteed by this, but it's a good proxy for WebAuthn capability
    } catch (e) {
      return false;
    }
  }

  /**
   * Register a new passkey with PRF extension.
   * Returns the credential ID and the symmetric key generated by the PRF.
   * 
   * @param {string} username - User identifier (usually wallet address or 'NexVault User')
   * @param {Uint8Array} salt - A random 32-byte salt for the PRF
   * @returns {Promise<{ credentialId: string, prfKey: CryptoKey }>}
   */
  async registerCredential(username = 'NexVault', salt) {
    if (!salt || salt.length !== 32) {
      throw new Error('BiometricManager: PRF salt must be exactly 32 bytes.');
    }

    const userId = crypto.getRandomValues(new Uint8Array(16));
    const challenge = crypto.getRandomValues(new Uint8Array(32));

    const createOptions = {
      publicKey: {
        rp: {
          name: 'NexVault Wallet',
          id: window.location.hostname || 'localhost',
        },
        user: {
          id: userId,
          name: username,
          displayName: username,
        },
        challenge: challenge,
        pubKeyCredParams: [
          { type: 'public-key', alg: -7 },  // ES256
          { type: 'public-key', alg: -257 } // RS256
        ],
        authenticatorSelection: {
          authenticatorAttachment: 'platform',
          userVerification: 'required',
          residentKey: 'required',
        },
        timeout: 60000,
        extensions: {
          prf: {
            eval: {
              first: salt
            }
          }
        }
      }
    };

    let credential;
    try {
      credential = await navigator.credentials.create(createOptions);
    } catch (error) {
      console.error('Biometric registration failed:', error);
      throw new Error('Failed to register biometric credential. Ensure your device supports FaceID/TouchID/Windows Hello.');
    }

    const extensionResults = credential.getClientExtensionResults();
    if (!extensionResults.prf || !extensionResults.prf.enabled) {
      throw new Error('Biometric PRF extension is not supported on this device/browser combination.');
    }

    if (!extensionResults.prf.results || !extensionResults.prf.results.first) {
      throw new Error('Biometric PRF failed to return a valid key.');
    }

    // The PRF result is an ArrayBuffer (usually 32 bytes)
    const prfOutput = extensionResults.prf.results.first;

    // Convert the raw PRF output into a CryptoKey for AES-GCM
    const prfKey = await crypto.subtle.importKey(
      'raw',
      prfOutput,
      { name: 'AES-GCM', length: 256 },
      false, // non-exportable
      ['encrypt', 'decrypt']
    );

    return {
      credentialId: cryptoEngine._arrayBufferToBase64(credential.rawId),
      prfKey
    };
  }

  /**
   * Assert (authenticate) using an existing passkey and retrieve the PRF key.
   * 
   * @param {string} credentialIdBase64 - The credential ID to request
   * @param {Uint8Array} salt - The same 32-byte salt used during registration
   * @returns {Promise<CryptoKey>} The symmetric key generated by the PRF
   */
  async getPrfKey(credentialIdBase64, salt) {
    if (!salt || salt.length !== 32) {
      throw new Error('BiometricManager: PRF salt must be exactly 32 bytes.');
    }

    const challenge = crypto.getRandomValues(new Uint8Array(32));
    const credentialId = cryptoEngine._base64ToArrayBuffer(credentialIdBase64);

    const getOptions = {
      publicKey: {
        challenge: challenge,
        rpId: window.location.hostname || 'localhost',
        allowCredentials: [{
          type: 'public-key',
          id: credentialId,
          transports: ['internal']
        }],
        userVerification: 'required',
        timeout: 60000,
        extensions: {
          prf: {
            eval: {
              first: salt
            }
          }
        }
      }
    };

    let credential;
    try {
      credential = await navigator.credentials.get(getOptions);
    } catch (error) {
      console.error('Biometric authentication failed:', error);
      throw new Error('Biometric authentication failed or was cancelled.');
    }

    const extensionResults = credential.getClientExtensionResults();
    
    if (!extensionResults.prf || !extensionResults.prf.results || !extensionResults.prf.results.first) {
      throw new Error('Biometric PRF failed to return a valid key during authentication.');
    }

    const prfOutput = extensionResults.prf.results.first;

    // Convert the raw PRF output into a CryptoKey for AES-GCM
    const prfKey = await crypto.subtle.importKey(
      'raw',
      prfOutput,
      { name: 'AES-GCM', length: 256 },
      false, // non-exportable
      ['encrypt', 'decrypt']
    );

    return prfKey;
  }
}

const biometricManager = new BiometricManager();
export default biometricManager;
